// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbBIDyPHvZdPG2owgqRIfvJfS4E7gMdyU',
    appId: '1:474831192309:web:51fb71abf3a389743645bc',
    messagingSenderId: '474831192309',
    projectId: 'auto-hiring-app-587b0',
    authDomain: 'auto-hiring-app-587b0.firebaseapp.com',
    storageBucket: 'auto-hiring-app-587b0.appspot.com',
    measurementId: 'G-SCES1X8R1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXk37a4cGPRTF_COO1tNMI4irhAsCeV2Q',
    appId: '1:474831192309:android:35d776b812b058a43645bc',
    messagingSenderId: '474831192309',
    projectId: 'auto-hiring-app-587b0',
    storageBucket: 'auto-hiring-app-587b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmkxIZ_q6jp0cnLWkX_WsRFu5xyxvZEso',
    appId: '1:474831192309:ios:97a3f0c6a680c0173645bc',
    messagingSenderId: '474831192309',
    projectId: 'auto-hiring-app-587b0',
    storageBucket: 'auto-hiring-app-587b0.appspot.com',
    iosBundleId: 'com.example.autohiringapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmkxIZ_q6jp0cnLWkX_WsRFu5xyxvZEso',
    appId: '1:474831192309:ios:519964174166d3643645bc',
    messagingSenderId: '474831192309',
    projectId: 'auto-hiring-app-587b0',
    storageBucket: 'auto-hiring-app-587b0.appspot.com',
    iosBundleId: 'com.example.autohiringapp.RunnerTests',
  );
}
